[build]
  publish = "/"

# Redirect root to login page
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 301

# Redirect all 404s to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
